linters:
  disable-all: true
  enable:
    - staticcheck
    - typecheck
    - ineffassign
    - revive
    - errcheck
    - nilerr
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
          - typecheck
